name: CI Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Compile Java code
        run: |
          mkdir -p out
          javac -d out $(find src/main -name "*.java")

      - name: Run tests
        run: |
          javac -d out $(find src/test -name "*.java")
          java -cp out org.junit.runner.JUnitCore $(find src/test -name "*Test.java" | sed 's/\.java$//')
